import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@component/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const date = new Date().getFullYear();
  return (
    <>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app and edited by Leonardo Diman" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={ styles.header }>
        <nav>
          <img src="" alt="" />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About us</a>
        </nav>
      </header>
      <main className={ styles.main }>
        <h1>
          Welcome!
        </h1>
        <span>Browse to find events</span>
        <a href='/events/london'>
          <h2>Events in London</h2>
          <img src="" alt="" />
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore, porro! Laboriosam repellendus nesciunt sed quas vitae. Maxime dolore pariatur voluptatum nihil, voluptatem natus labore reprehenderit nam eius distinctio? Tempore, non?</p>
        </a>
        <a href='/events/sanfrancisco'>
          <h2>Events in San Francisco</h2>
          <img src="" alt="" />
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore, porro! Laboriosam repellendus nesciunt sed quas vitae. Maxime dolore pariatur voluptatum nihil, voluptatem natus labore reprehenderit nam eius distinctio? Tempore, non?</p>
        </a>
        <a href='/events/barcelona'>
          <h2>Events in Barcelona</h2>
          <img src="" alt="" />
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore, porro! Laboriosam repellendus nesciunt sed quas vitae. Maxime dolore pariatur voluptatum nihil, voluptatem natus labore reprehenderit nam eius distinctio? Tempore, non?</p>
        </a>
      </main>

      <footer className={ styles.footer }>
        <p> {date} | Desenvolvido por Leonardo Diman</p>
      </footer>
    </>
  )
}
